### PR TITLE
Fix and cleanup cvar callbacks

### LINKED ISSUE #2314: AddChangeCallback not used correctly
Can't get the value from the cvar inside the callback, need to use input parameter

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #2314

### CODE REVIEW

File: lua/starfall/toolscreen.lua [hunk 1]
```diff
@@ -195,7 +194,5 @@ local function toggle_toolscreen(enabled)
 		end
 	end
 end
-CreateClientConVar("starfall_toolscreen", "1", true, false, "Enable Starfall custom toolgun screen animation", 0, 1)
-cvars.AddChangeCallback("starfall_toolscreen", function(_, _, value)
-	toggle_toolscreen(value == "1")
-end)
+local toolScreenCvar = CreateClientConVar("starfall_toolscreen", "1", true, false, "Enable Starfall custom toolgun screen animation", 0, 1)
+SF.CvarCallback(cvar, function(val) toggle_toolscreen(val) end, toolScreenCvar:GetBool(), true)
```
Comment (adamnejm) [inline lua/starfall/toolscreen.lua]: Should be `toolScreenCvar` instead of `cvar`

**Review by adamnejm — CHANGES_REQUESTED** [review]

File: lua/starfall/toolscreen.lua (hunk 1 above)
Comment (thegrb93) [reply lua/starfall/toolscreen.lua]: Thx, will test all the cvars sometime later.

**Comment by thegrb93** [comment]
I think I'll change it so that the cvar create function can go directly in it and the last parameter will be the var type as a string.

File: lua/starfall/sflib.lua [hunk 2]
```diff
@@ -134,6 +134,21 @@ end
...
+	if isnumber(curval) then
+		converter = function(x) return tonumber(x) or tonumber(cvar:GetDefault()) end
+	elseif isstring(curval) then
+		converter = function(x) return x end
+	elseif isbool(curval) then
+		converter = function(x) return tobool(x) end
+	else
+		error("Unsupported type!")
+	end
+	cvars.AddChangeCallback(cvar:GetName(), function(_,_,val) callback(converter(val)) end)
```
Comment (Cheatoid) [inline lua/starfall/sflib.lua]: if this runs multiple times, you are gonna have multiple callbacks, pass a callback id (3rd argument) and call RemoveChangeCallback before adding to remove the old one...
