### PR TITLE
Fix writing colors in SF.TableToString

### LINKED ISSUE #1326: net.write/readTable does not work well for colors
When sending a color through net.write/readTable, it is not received as a color, but rather as a table with the string keys r,g,b, and a. As a result, no Color library methods can be called on the received color. If you use net.write/readColor instead, the color is properly received and the type is Color.

Example code:
```
if SERVER then
    local c = Color(255,0,0)
    local cClone = c:clone() --works
    
    timer.simple(3, function()
        net.start("sendColor")
        net.writeTable({
            Color = c
        })
        net.send()
    end)
end


if CLIENT then
    net.receive("sendColor", function()
        local c = net.readTable().Color
        print(type(c)) --table
        local cClone = c:clone() --error: attempt to call method 'clone' (a nil value)
    end)
end
```

### PR DESCRIPTION
**Pull request by ANormalTwig**
Fixes #1326

### CODE REVIEW

File: lua/starfall/sflib.lua [hunk 1]
```diff
@@ -1096,7 +1096,7 @@ do
 		local tableLookup = {}
 
 		local function typeToString(val)
-			local func = typetostringfuncs[TypeID(val)]
+			local func = typetostringfuncs[IsColor(val) and TYPE_COLOR or TypeID(val)]
```
Comment (thegrb93) [inline lua/starfall/sflib.lua:1099]: Can you instead do this inside `typetostringfuncs[TYPE_TABLE] = function(ss, val)` (line 1103)

`if IsColor(val) then return typetostringfuncs[TYPE_COLOR](ss, val) end`

**Comment by thegrb93** [comment]
Thx, looks good
