### PR TITLE
Add Hologram.followBone and fix clientside re-parenting offset desync

### LINKED ISSUE #815: Add bone arguement to entities.setParent
https://wiki.facepunch.com/gmod/Entity:FollowBone

### PR DESCRIPTION
**Pull request by adamnejm**
- Globalized the function responsible for checking whether parent chain length is too long as `SF.ParentChainTooLong`
- Added shared `Hologram.followBone(Entity parent, number bone)`
- Modified the previous clientside hologram re-parenting fix to also use it with `followBone`
- **Didn't** add a new permission, using `entities.setParent` instead, I think it's sufficient
- Made clientside's hologram `setPos` and `setAng` also update it's relative positions and angles for the re-parent fix *(weird how nobody noticed that before)*

I didn't test `followBone` with other players' PAC outfits, but mine doesn't seem to be affected in any way on a local server.

Fixes #815, #1282

### CODE REVIEW

File: lua/starfall/libs_sh/holograms.lua [hunk 1]
```diff
@@ -332,45 +356,68 @@ else
...
+	local function clearParentFix(ent)
+		if ent.sf_parent then
+			ent.sf_parent.sf_children[ent] = nil
+			ent.sf_parent = nil
+		end
+	end
+	
+	local function setParentFix(ent, parent, bone, func)
+		if not parent.sf_children then
+			parent.sf_children = {}
```
Comment (adamnejm) [inline lua/starfall/libs_sh/holograms.lua:368]: Should this use `SF.EntityTable`? It will only ever contain hologram entities.

**Comment by adamnejm** [comment]
Could also convert the whole `followBone` to be included in `setParent` by adding an optional boolean argument, if True `FollowBone`, otherwise regular `SetParent`. Little weird, but can do it if you want.

File: lua/starfall/libs_sh/holograms.lua (hunk 1 above)
Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:368]: Yeah I think that would be best and it should work fine in this case.

Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:368]: Or you can call clearParentFix in the removeHolo functions

Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:368]: These can be moved above the `return function(instance)` as well

Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:368]: `hologramOnDestroy` I mean is where the clearParentFix should go

File: lua/starfall/libs_sh/holograms.lua [hunk 2]
```diff
@@ -332,45 +356,68 @@ else
...
+	-- @param Entity? parent Entity parent (nil to unparent)
+	-- @param number bone Bone ID
+	function hologram_methods:followBone(parent, bone)
+		local holo = getent(self)
+		checkpermission(instance, holo, "hologram.setParent")
+		
+		if parent ~= nil then
+			parent = getent(parent)
+			checkluatype(bone, TYPE_NUMBER)
+
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:414]: parentChainTooLong should be checked in the clientside too right?

Comment (adamnejm) [reply lua/starfall/libs_sh/holograms.lua:414]: Clientside Hologram didn't have the check originally and I couldn't find much info about this bug so I assumed it only affectes serverside parents.  
I can implement it though.

Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:414]: Probably good to be safe

**Comment by thegrb93** [comment]
> Could also convert the whole `followBone` to be included in `setParent` by adding an optional boolean argument, if True `FollowBone` would be used, otherwise the regular `SetParent`. Little weird, but can do it if you want.

This is probably the best option because most people will search 'parent' in the docs and 'follow' will be missed.

**Comment by adamnejm** [comment]
Feel free to check clientside `Hologram.setParent(Entity parent, number|string? attachment, boolean? bone)`, it's tested and should be OK.  
Need to extensively test serverside tho so I'm converting this to a draft for now.  
  
Also, this will close #1282.

File: lua/starfall/libs_sh/holograms.lua [hunk 3]
```diff
@@ -84,6 +117,7 @@ instance:AddHook("initialize", function()
 end)
 
 local function hologramOnDestroy(holo)
+	if CLIENT then clearParentFix(holo) end
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:120]: Maybe the `if CLIENT` can be moved inside these functions? Otherwise, I think setParent needs these `if CLIENT` checks too

File: lua/starfall/libs_sh/holograms.lua [hunk 4]
```diff
@@ -331,46 +371,45 @@ else
...
+				else
+					attachment = attachment or -1
+					checkluatype(attachment, TYPE_NUMBER)
+				end
 			end
-
-			if holo.sf_parent then
-				holo.sf_parent.sf_children[holo] = nil
+			
+			local parentFunc = bone and "FollowBone" or "SetParent"
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:398]: Instead of a string, you can just give it the function, `holo.FollowBone` `holo.SetParent`

Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:398]: Then you just call it with `data.func(child, parent, data.bone)`

File: lua/starfall/libs_sh/holograms.lua [hunk 5]
```diff
@@ -331,46 +371,45 @@ else
...
-			checkluatype(attachment, TYPE_NUMBER)
-
-			if not parent.sf_children then
-				parent.sf_children = {}
+		
+		if parent ~= nil then
+			parent = getent(parent)
+			if bone ~= nil then checkluatype(bone, TYPE_BOOL) end
+			if bone then
+				attachment = attachment or 0
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:387]: I'd delete this line

File: lua/starfall/libs_sh/holograms.lua [hunk 6]
```diff
@@ -331,46 +371,45 @@ else
...
+				checkluatype(attachment, TYPE_NUMBER)
+			else
+				if isstring(attachment) then
+					attachment = parent:LookupAttachment(attachment)
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:391]: Probably could throw an error if the lookup fails

File: lua/starfall/libs_sh/holograms.lua (hunk 5 above)
Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:387]: What if we also add a bone lookup since the attachment path has it.

File: lua/starfall/libs_sh/holograms.lua [hunk 7]
```diff
@@ -331,46 +371,45 @@ else
...
+				else
+					attachment = attachment or -1
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:393]: Can delete this too

**Comment by thegrb93** [comment]
I improved the attachment var checking. Mind copying that to the entities.lua setParent?

File: lua/starfall/libs_sh/holograms.lua (hunk 4 above)
Comment (adamnejm) [reply lua/starfall/libs_sh/holograms.lua:396]: It'd still be `data.func(holo, child, parent, data.bone)`, but the reason I'm not storing functions directly is to allow monkey-patching. Will change it tho, sure.

**Comment by adamnejm** [comment]
In your improvements:
```lua
attachment = bone and parent:LookupBone(attachment) or parent:LookupAttachment(attachment)
```
If the `LookupBone` fails, it'll still do `LookupAttachment`, may seem good at first since the last function will return 0 or -1, but what if some weird model has bones and attachments with the same name? Not sure if even possible in Source, but I'd still use an `if`.  
  
Also
```lua
if isnumber(attachment) then
elseif isstring(attachment) then
    attachment = bone and parent:LookupBone(attachment) or parent:LookupAttachment(attachment)
else
    SF.ThrowTypeError("string or number", SF.GetType(attachment), 2)
end
```
should be
```lua
if isstring(attachment) then
    attachment = bone and parent:LookupBone(attachment) or parent:LookupAttachment(attachment)
elseif not isnumber(attachment) then
    SF.ThrowTypeError("string or number", SF.GetType(attachment), 2)
end
```

File: lua/starfall/libs_sh/holograms.lua (hunk 3 above)
Comment (adamnejm) [reply lua/starfall/libs_sh/holograms.lua:120]: These functions are never used serverside though, `Hologram.setParent` is only defined on the client, since to parent holos on the server you just use `Entity.setParent`.  
Have I misunderstood what you meant or can this conversation be resolved?

**Comment by adamnejm** [comment]
How about changes from the last 2 commits?  
Now you can also do `holo:setParent(parent, nil, true)` and it'll default to bone `0`

**Comment by adamnejm** [comment]
Should be ready to review after we resolve the 2 conversations you started above. If you're not OK with the changes I made to your commits I can revert them.

**Comment by thegrb93** [comment]
Ok, good catch. I thought the lookupBone would return -1 on failure.

File: lua/starfall/libs_sh/holograms.lua (hunk 4 above)
Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:397]: I guess it's fine as is

File: lua/starfall/libs_sh/holograms.lua (hunk 3 above)
Comment (thegrb93) [reply lua/starfall/libs_sh/holograms.lua:120]: All right, that makes sense.

**Comment by thegrb93** [comment]
My last complaint is attachment shouldn't default to 0 imo. Who would do `setParent(ent, nil, true)` instead of `setParent(ent, 0, true)`? It should instead throw an error

**Comment by thegrb93** [comment]
Probably need to try again

**Comment by thegrb93** [comment]
There it is, I see it now

File: lua/starfall/libs_sh/holograms.lua [hunk 8]
```diff
@@ -383,15 +383,13 @@ else
 		if parent ~= nil then
 			parent = getent(parent)
 			if bone ~= nil then checkluatype(bone, TYPE_BOOL) end
-			if attachment ~= nil then
+			if attachment ~= nil or bone then
 				if isstring(attachment) then
 					attachment = bone and parent:LookupBone(attachment) or parent:LookupAttachment(attachment)
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:388]: Gotta change this to an if-else since LookupBone returns nil instead of -1

Comment (adamnejm) [reply lua/starfall/libs_sh/holograms.lua]: Well yeah, I pointed this [here](https://github.com/thegrb93/StarfallEx/pull/1281#issuecomment-1069096296), just thought you didn't care about such case or it was impossible. Changed it to an `else-if` now.

File: lua/starfall/libs_sh/holograms.lua [hunk 9]
```diff
@@ -385,7 +385,11 @@ else
 			if bone ~= nil then checkluatype(bone, TYPE_BOOL) end
 			if attachment ~= nil or bone then
 				if isstring(attachment) then
-					attachment = bone and parent:LookupBone(attachment) or parent:LookupAttachment(attachment)
+					if bone then
+						attachment = parent:LookupBone(attachment) or 0
```
Comment (thegrb93) [inline lua/starfall/libs_sh/holograms.lua:389]: or -1

File: lua/starfall/libs_sh/holograms.lua (hunk 8 above)
Comment (adamnejm) [reply lua/starfall/libs_sh/holograms.lua]: Wrong name of the last commit, actually fixes edge case where `bone` is used, but attachment is found instead and parents to a random bone

File: lua/starfall/libs_sh/holograms.lua (hunk 9 above)
Comment (adamnejm) [reply lua/starfall/libs_sh/holograms.lua:389]: IIRC -1 was causing issues actually, making the holos disappear or teleport to world origin and not actually parent, will test it out quickly, give me a second

**Comment by thegrb93** [comment]
I'm tempted to change this so that the `bone` arg is a bone number or name instead of a bool. Then either var is optional, and if both are set then it errors. Makes better sense I think.

File: lua/starfall/libs_sh/holograms.lua (hunk 9 above)
Comment (adamnejm) [reply lua/starfall/libs_sh/holograms.lua:389]: Oh never mind, I see what you meant, the `if attachment < 0 or attachment > 255` will catch it and error

**Comment by adamnejm** [comment]
Hmmm, I like it more this way, but change it if you want :)

**Comment by thegrb93** [comment]
Could we make the hologram setParent shared and remove the hologram-only stuff from the entities setParent?

**Comment by adamnejm** [comment]
Yeah I guess that'd be nice. I was also thinking about your previous suggestion about moving away from the `attachment` argument being interchangeable with what's provided to the `FollowBone`, it would reduce the unnecessary complexity that's currently making the `SetParent` functions bulky and hard to read.  
Will do this when I find some time.

**Comment by thegrb93** [comment]
@adamnejm

**Comment by thegrb93** [comment]
I actually have an idea to make this even cleaner. Maybe I'll try that

**Comment by thegrb93** [comment]
Something like
```lua
local parentFixer = {
	__index = {
		updateTransform = function(self, data)
			data.pos, data.ang = WorldToLocal(self.ent:GetPos(), self.ent:GetAngles(), data.child:GetPos(), data.child:GetAngles())
		end,

		applyTransform = function(self, data)
			local pos, ang = LocalToWorld(data.pos, data.ang, self.ent:GetPos(), self.ent:GetAngles())
			data.child:SetPos(pos)
			data.child:SetAngles(ang)
		end,
		
		setParents = {
			entity = {
				function(self)
					self.child:SetParent(self.parent)
				end,
				function(self)
					self.child:SetParent()
				end
			},
			attachment = {
				function(self)
					self.child:SetParent(self.parent)
					self.child:Fire("SetParentAttachmentMaintainOffset", self.param, 0.01)
				end,
				function(self)
					self.child:SetParent()
				end
			},
			bone = {
				function(self)
					self.child:FollowBone(self.parent, self.param)
				end,
				function(self)
					self.child:FollowBone()
				end
			}
		},

		add = function(self, child, type, param)
			local parent, unparent = unpack(self.setParents[type])
			local data = {
				parent = self.ent,
				child = child,
				setParent = parent,
				unParent = unparent,
				param = param
			}
			self:updateTransform(data)
			self.children[child] = data
		end,

		fix = function(self)
			for child, data in pairs(self.children) do	
				if child:IsValid() then
					self:applyTransform(data)
					data:setParent()
				else
					self.children[child] = nil
				end
			end
		end,
	},
	__call = function(meta, ent, parent)
		return setmetatable({
			ent = ent,
			parent = parent,
			children = {}
		}, meta)
	end
}
setmetatable(parentFixer, parentFixer)
```

**Comment by thegrb93** [comment]
Here we go, this should be magnitudes better

```lua
local SF_Parent = {
	__index = {
		updateTransform = function(self)
			self.pos, self.ang = WorldToLocal(self.parent:GetPos(), self.parent:GetAngles(), data.ent:GetPos(), data.ent:GetAngles())
		end,

		applyTransform = function(self)
			local pos, ang = LocalToWorld(self.pos, self.ang, self.parent:GetPos(), self.parent:GetAngles())
			self.ent:SetPos(pos)
			self.ent:SetAngles(ang)
		end,
		
		setParents = {
			entity = {
				function(self)
					self.ent:SetParent(self.parent)
				end,
				function(self)
					self.ent:SetParent()
				end
			},
			attachment = {
				function(self)
					self.ent:SetParent(self.parent)
					self.ent:Fire("SetParentAttachmentMaintainOffset", self.param, 0.01)
				end,
				function(self)
					self.ent:SetParent()
				end
			},
			bone = {
				function(self)
					self.ent:FollowBone(self.parent, self.param)
				end,
				function(self)
					self.ent:FollowBone()
				end
			}
		},

		setParent = function(self, parent, type, param)
			if self.parent and self.parent:IsValid() then
				self.parent.sf_parent.children[self.ent] = nil
				self:unParentType()
			end
			if parent then
				self.parent = parent
				self.param = param
				self.setParentType, self.unParentType = unpack(self.setParents[type])

				local sf_parent = parent.sf_parent
				if sf_parent then
					sf_parent.children[self.ent] = self
				end
				self:updateTransform()
				self:setParentType()
			else
				self.parent = nil
				self.param = nil
				self.setParentType = nil
				self.unParentType = nil
			end
		end,

		fix = function(self)
			if self.parent and self.parent:IsValid() then
				self:applyTransform()
				self:setParentType()
			end
			for child, data in pairs(self.children) do	
				if child:IsValid() then
					data:applyTransform()
					data:setParentType()
				else
					self.children[child] = nil
				end
			end
		end,
	},
	__call = function(meta, parent, child, type, param)
		if not parent.sf_parent then
			parent.sf_parent = setmetatable({
				ent = parent,
				children = {}
			}, meta)
		end

		local sf_parent = child.sf_parent
		if not sf_parent then
			sf_parent = setmetatable({
				ent = child,
				children = {}
			}, meta)
			child.sf_parent = sf_parent
		end
		sf_parent:setParent(parent, type, param)
	end
}
setmetatable(SF_Parent, SF_Parent)

if CLIENT then
	-- Need to fix the children and parent of any entity retransmitted
	hook.Add("NotifyShouldTransmit", "StarfallHologramReparent", function(ent)
		local sf_parent = ent.sf_parent
		if sf_parent then
			sf_parent:fix()
		end
	end)
end


function hologram_methods:setParent(parent, attachment, bone)
	local child = getholo(self)
	checkpermission(instance, child, "hologram.setParent")
	if attachment~=nil and bone~=nil then SF.Throw("Can't have both attachment and bone args set!", 2) end
	if parent ~= nil then
		parent = getent(parent)
		if parentChainTooLong(parent, child) then SF.Throw("Parenting chain of entities can't exceed 16 or crash may occur", 2) end

		local param, type
		if bone~=nil then
			type = "bone"
			if isnumber(bone) then
			elseif isstring(bone) then
				bone = parent:LookupBone(bone) or -1
			else
				SF.ThrowTypeError("string or number", SF.GetType(bone), 2)
			end
			if bone < 0 or bone > 255 then SF.Throw("Invalid bone provided", 2) end
			param = bone
		elseif attachment~=nil then
			type = "attachment"
			if isnumber(attachment) then
			elseif isstring(attachment) then
				attachment = parent:LookupAttachment(attachment)
			else
				SF.ThrowTypeError("string or number", SF.GetType(attachment), 2)
			end
			if attachment < 0 or attachment > 255 then SF.Throw("Invalid attachment provided", 2) end
			param = attachment
		else
			type = "entity"
		end

		SF_Parent(parent, child, type, param)
	else
		local sf_parent = child.sf_parent
		if sf_parent then
			sf_parent:setParent()
		end
	end
end
```

**Comment by thegrb93** [comment]
@adamnejm mind testing?

**Comment by thegrb93** [comment]
Rapid testing it is
